apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend
  namespace: promhub
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt"
spec:
  rules:
  - host: api.promcat.io
    http:
      paths:
      - backend:
          serviceName: backend
          servicePort: 8080
  tls:
  - hosts:
    - api.promcat.io
    secretName: backend-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: promhub
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt"
spec:
  rules:
  - host: promcat.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 3000
  tls:
  - hosts:
    - promcat.io
    secretName: frontend-tls