# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: _json_key
        password: ${{ secrets.GRC_REGISTRY_SECRET }}
        registry: gcr.io
        dockerfile: Dockerfile.server
        repository: mateo-burillo-ns/promcat-backend
        tags: latest
    - name: build and push docker image
      uses: docker/build-push-action@v1
      with:
        username: _json_key
        password: ${{ secrets.GRC_REGISTRY_SECRET }}
        registry: gcr.io
        dockerfile: Dockerfile.dbimport
        repository: mateo-burillo-ns/promcat-dbimport
        tags: latest